### ISSUE TITLE
in not compatible

### ISSUE THREAD

**Issue by Trip20** [ahmoylaw/RegexTrainer-Descriptions#10]
i tried to install your plug-in in my notepad ++ ver 7.9.5 64 bit but it tells me it is not compatible with this version of notepad. suggestions? thanks

**Comment by ahmoylaw** [comment]
May i know what is your installation process?  I just installed the 7.9.5 64bit and installed the Regex Trainer thru Plugins Admin without any issues.

**Comment by Trip20** [comment]
hi ahmoylaw.Configuration => import => import plug-in => RegexTrainer.dll. I hope I didn't get the procedure wrong.

**Comment by ahmoylaw** [comment]
Hi, can you try these steps?  (make sure you removed the RegexTrainer.dll previously copied/installed)
1. Select "Plugins" (at the main menu bar)
2. Select "Plugins Admin..."
3. From the Plugin list inside the "Plugin Admin" screen, try to locate/find "Regex Trainer", check it and click at the "Install" button
4. Notepad++ will then download the correct dll for you (may restart notepad++ to finish the installation)

**Comment by Trip20** [comment]
hi ahmoylaw, thank you for your interest. I tried to do as indicated
but I have not had any positive feedback except the same incompatibility
message. Thanks

**Comment by ahmoylaw** [comment]
emmm... weird.  Can you try one more thing?
1. rename your current notepad++ folder (so that windows will throw error if you try to run notepad++ from the start menu or activate file associated with npp
2. download the portable npp 64 just simply extract it into any folder
3. run the portable npp 64
4. select plugins from the menu bar and plugins Admin...  to download the regex trainer again

btw, the regex trainer is written c# and requires .net ver 4.0 to run properly if I'm not mistaken

**Comment by Trip20** [comment]
ok solved.After the recent reinstallation of the o.s. on my pc i neglected to reinstall the .net libraries. unforgivable. Thanks again
