### ISSUE TITLE
Syntax highlighting disappears after closing plugin 

### ISSUE THREAD

**Issue by gasheva** [ahmoylaw/RegexTrainer-Descriptions#3]
When I close plugin window syntax highlighting disappears 
![image](https://user-images.githubusercontent.com/65405671/99140503-9a6e6800-2653-11eb-8fe3-5b6e0cbf09d3.png)
![image](https://user-images.githubusercontent.com/65405671/99140524-be31ae00-2653-11eb-8c36-3d8a54b3b7ad.png)

**Comment by ahmoylaw** [comment]
Hi Gashewa,

I will try to look on this issue but currently I’m very busy with other projects. Will try my best to figure out how to fix this whenever i have free time to look into this.

From,
Law

**Comment by ahmoylaw** [comment]
Hi Gashewa,

Actually the regex trainer should only use on a plain text only since 
I don’t think notepad++ will allow two syntax hilighters to operate at the same time. Maybe what i can do is to save the current syntax hilighter and restore it once the window is closed, provided only if notepad++ has the api to save and restore the hilighter. If i remember correctly, my code will just reset the hilighter to none to remove the previous highlighted ‘plain’ text.


From,
Law

**Comment by znsoooo** [comment]
@gasheva You can set the Language to another and set back to get the original hilighter.
But I think this is not a perfect idea. @ahmoylaw Maybe **reset the system language highlighter firstly**, then do your plugin highlighting secondly, can solve this problem?

And I think add a **button** to set to start search maybe better. Because sometimes the regular expression haven't input completely, but the automatic search start up caused the editor to be very stuck, and sometimes will exit in error.

**Comment by znsoooo** [comment]
I noticed that in the `Mark` panel, `Mark All` and `Clear all marks` can highlight and unhighlight text without affecting other highlighted text. Can you refer to the method implemented in this part? Just a suggestion. :) @gasheva

**Comment by ahmoylaw** [comment]
Hi Gashewa,

This RegexTrainer is just a very simple plugin that i wrote long time ago and to simplify the code, whenever user close the panel, it will just reset the hilighter back to default.

Thanks,
Law
